apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kg-rca-server.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-server.labels" . | nindent 4 }}
data:
  # Global config
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  DOMAIN: {{ .Values.global.domain | quote }}

  # Neo4j config
  NEO4J_URI: "neo4j://{{ include "kg-rca-server.fullname" . }}-neo4j:7687"
  NEO4J_USER: {{ .Values.neo4j.auth.username | quote }}

  # Kafka config
  KAFKA_BROKERS: "{{ include "kg-rca-server.fullname" . }}-kafka:9092"

  # PostgreSQL config
  POSTGRES_HOST: "{{ include "kg-rca-server.fullname" . }}-postgresql"
  POSTGRES_DB: {{ .Values.postgresql.auth.database | quote }}
  POSTGRES_USER: {{ .Values.postgresql.auth.username | quote }}
