{{- if .Values.kafka.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kg-rca-server.fullname" . }}-kafka
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-server.labels" . | nindent 4 }}
    app: kafka
spec:
  type: {{ .Values.kafka.service.type }}
  ports:
  - port: {{ .Values.kafka.service.port }}
    targetPort: 9092
    protocol: TCP
    name: kafka
  selector:
    app: kafka
    {{- include "kg-rca-server.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kg-rca-server.fullname" . }}-kafka-headless
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-server.labels" . | nindent 4 }}
    app: kafka
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9092
    targetPort: 9092
    protocol: TCP
    name: kafka
  - port: 9093
    targetPort: 9093
    protocol: TCP
    name: kafka-internal
  selector:
    app: kafka
    {{- include "kg-rca-server.selectorLabels" . | nindent 4 }}
{{- end }}
