{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kg-rca-server.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-server.labels" . | nindent 4 }}
    app: postgresql
spec:
  serviceName: {{ include "kg-rca-server.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
      {{- include "kg-rca-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: postgresql
        {{- include "kg-rca-server.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: postgresql
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        ports:
        - containerPort: 5432
          name: postgresql
        env:
        - name: POSTGRES_DB
          value: {{ .Values.postgresql.auth.database }}
        - name: POSTGRES_USER
          value: {{ .Values.postgresql.auth.username }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "kg-rca-server.fullname" . }}-secrets
              key: postgresql-password
        resources:
          {{- toYaml .Values.postgresql.resources | nindent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.postgresql.persistence.size }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kg-rca-server.fullname" . }}-postgresql
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-server.labels" . | nindent 4 }}
    app: postgresql
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgresql
  selector:
    app: postgresql
    {{- include "kg-rca-server.selectorLabels" . | nindent 4 }}
{{- end }}
