{{- if .Values.rbac.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kg-client.serviceAccountName" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "kg-client.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kg-client.fullname" . }}
  labels:
    {{- include "kg-client.labels" . | nindent 4 }}
rules:
  # Event Exporter permissions
  - apiGroups: [""]
    resources:
      - events
    verbs:
      - get
      - list
      - watch

  # State Watcher permissions
  - apiGroups: [""]
    resources:
      - pods
      - services
      - configmaps
      - secrets
      - nodes
      - namespaces
    verbs:
      - get
      - list
      - watch

  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - daemonsets
      - statefulsets
    verbs:
      - get
      - list
      - watch

  # Vector log collection permissions
  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get
      - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kg-client.fullname" . }}
  labels:
    {{- include "kg-client.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kg-client.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kg-client.serviceAccountName" . }}
    namespace: {{ .Values.namespace }}
{{- end }}
