apiVersion: v1
kind: Pod
metadata:
  name: pod-missing-secret
  namespace: buglab
  labels:
    app: bug-secret
    scenario: secret-missing
spec:
  restartPolicy: Always
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c", "echo 'Starting...'; sleep 3600"]
      env:
        - name: SECRET_VALUE
          valueFrom:
            secretKeyRef:
              name: nonexistent-secret
              key: password
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi