apiVersion: v1
kind: Pod
metadata:
  name: terminating-stuck
  namespace: buglab
  labels:
    app: bug-terminating
    scenario: terminating-stuck
  finalizers:
    - example.com/fake-finalizer
spec:
  restartPolicy: Always
  terminationGracePeriodSeconds: 60
  containers:
    - name: ignores-sigterm
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
        - |
          trap "" SIGTERM
          echo "Pod configured to ignore SIGTERM signal"
          echo "This simulates a stuck terminating pod"
          while true; do
            echo "Running... (ignoring termination signals)"
            sleep 30
          done
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi