apiVersion: apps/v1
kind: Deployment
metadata:
  name: oom-test
  namespace: kg-testing
  labels:
    app: oom-test
    test-scenario: oom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oom-test
  template:
    metadata:
      labels:
        app: oom-test
        test-scenario: oom
    spec:
      containers:
      - name: app
        image: kg-test-apps:latest
        imagePullPolicy: Never
        command: ["python3", "-u", "/app/oom-killer.py"]
        resources:
          requests:
            memory: "32Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"  # Low limit to trigger OOM quickly
            cpu: "50m"
---
apiVersion: v1
kind: Service
metadata:
  name: oom-test
  namespace: kg-testing
spec:
  selector:
    app: oom-test
  ports:
  - port: 80
    targetPort: 8080
