{{- if .Values.alertReceiver.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-alert-receiver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-agent.labels" . | nindent 4 }}
    component: alert-receiver
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kg-rca-agent.selectorLabels" . | nindent 4 }}
    component: alert-receiver
{{- end }}
