apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-deregister-cluster
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: deregister
        image: anuragvishwa/kafka-producer-minimal:1.0.0
        command:
        - /bin/bash
        - -c
        - |
          echo "🪦 Deregistering cluster {{ .Values.client.id }}..."

          # Send tombstone (null value) to remove from registry
          echo "{{ .Values.client.id }}:" | kafka-console-producer \
            --bootstrap-server {{ .Values.client.kafka.brokers }} \
            --topic cluster.registry \
            --property "parse.key=true" \
            --property "key.separator=:" \
            --property "null.marker=" \
            {{- if .Values.client.kafka.sasl.enabled }}
            --producer-property "security.protocol={{ .Values.client.kafka.sasl.mechanism }}" \
            --producer-property "sasl.mechanism={{ .Values.client.kafka.sasl.mechanism }}" \
            --producer-property "sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"{{ .Values.client.kafka.sasl.username }}\" password=\"{{ .Values.client.kafka.sasl.password }}\";" \
            {{- end }}
            2>&1

          if [ $? -eq 0 ]; then
            echo "✅ Cluster {{ .Values.client.id }} deregistered successfully!"
          else
            echo "⚠️  Failed to deregister cluster {{ .Values.client.id }} (may not affect deletion)"
          fi
