{{- if .Values.eventExporter.enabled -}}
{{- $topicEvents := default "events.normalized" .Values.eventExporter.kafkaTopic -}}
{{- $topicRawEvents := .Values.eventExporter.rawTopic -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-event-exporter-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-agent.labels" . | nindent 4 }}
    component: event-exporter
data:
  config.yaml: |
    logLevel: debug
    logFormat: json
    maxEventAgeSeconds: 300
    route:
      routes:
        - match:
            - receiver: "kafka"
            {{- if $topicRawEvents }}
            - receiver: "kafka-raw"
            {{- end }}
    receivers:
      - name: "kafka"
        kafka:
          brokers:
            - {{ .Values.client.kafka.brokers }}
          topic: {{ $topicEvents }}
          clientId: "event-exporter-{{ .Values.client.id }}"
          compression: gzip
          layout: |
            {{ "{{" }} $event := . {{ "}}" }}
            {{ "{{" }} $event.ClientID = "{{ .Values.client.id }}" {{ "}}" }}
            {{ "{{" }} toJson $event {{ "}}" }}
          {{- if .Values.client.kafka.sasl.enabled }}
          tls:
            enable: true
          sasl:
            enabled: true
            username: "{{ "{{" }} .Env.KAFKA_SASL_USERNAME {{ "}}" }}"
            password: "{{ "{{" }} .Env.KAFKA_SASL_PASSWORD {{ "}}" }}"
            mechanism: {{ .Values.client.kafka.sasl.mechanism }}
          {{- end }}
      {{- if $topicRawEvents }}
      - name: "kafka-raw"
        kafka:
          brokers:
            - {{ .Values.client.kafka.brokers }}
          topic: {{ $topicRawEvents }}
          clientId: "event-exporter-raw-{{ .Values.client.id }}"
          compression: gzip
          {{- if .Values.client.kafka.sasl.enabled }}
          tls:
            enable: true
          sasl:
            enabled: true
            username: "{{ "{{" }} .Env.KAFKA_SASL_USERNAME {{ "}}" }}"
            password: "{{ "{{" }} .Env.KAFKA_SASL_PASSWORD {{ "}}" }}"
            mechanism: {{ .Values.client.kafka.sasl.mechanism }}
          {{- end }}
      {{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-event-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-agent.labels" . | nindent 4 }}
    component: event-exporter
spec:
  replicas: {{ .Values.eventExporter.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      {{- include "kg-rca-agent.selectorLabels" . | nindent 6 }}
      component: event-exporter
  template:
    metadata:
      labels:
        {{- include "kg-rca-agent.selectorLabels" . | nindent 8 }}
        component: event-exporter
      annotations:
        checksum/config: {{ toYaml .Values.eventExporter.config | sha256sum }}
        checksum/secret: {{ toYaml .Values.client.kafka.sasl | sha256sum }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      containers:
        - name: event-exporter
          image: "{{ .Values.eventExporter.image.repository }}:{{ .Values.eventExporter.image.tag }}"
          imagePullPolicy: {{ .Values.eventExporter.image.pullPolicy }}
          args:
            - -conf=/config/config.yaml
          env:
            - name: CLIENT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ include "kg-rca-agent.fullname" . }}-config
                  key: CLIENT_ID
            {{- if .Values.client.kafka.sasl.enabled }}
            # Kafka SASL Credentials from Secret
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "kg-rca-agent.fullname" . }}-secrets
                  key: kafka-sasl-username
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "kg-rca-agent.fullname" . }}-secrets
                  key: kafka-sasl-password
            {{- end }}
          resources:
            {{- toYaml .Values.eventExporter.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "kg-rca-agent.fullname" . }}-event-exporter-config
      restartPolicy: Always
{{- end }}
