{{- if .Values.heartbeat.enabled | default true }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-heartbeat
  labels:
    {{- include "kg-rca-agent.labels" . | nindent 4 }}
spec:
  schedule: "*/1 * * * *"  # Every minute
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: heartbeat
            image: edenhill/kcat:1.7.1
            command:
              - /bin/sh
              - -c
              - |
                HEARTBEAT='{"client_id":"{{ .Values.client.id }}","timestamp":"'$(date -u +%Y-%m-%dT%H:%M:%SZ)'"}'
                echo "$HEARTBEAT" | kcat -P \
                  -b {{ .Values.client.kafka.brokers }} \
                  -t cluster.heartbeat \
                  -K:: \
                  -k "{{ .Values.client.id }}"
{{- end }}
