---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-agent.labels" . | nindent 4 }}
    component: secrets
type: Opaque
stringData:
  # Client API Key (optional - leave empty if server doesn't require authentication)
  client-api-key: {{ .Values.client.apiKey | default "" | quote }}

  # Kafka SASL Credentials
  {{- if .Values.client.kafka.sasl.enabled }}
  kafka-sasl-mechanism: {{ .Values.client.kafka.sasl.mechanism | quote }}
  kafka-sasl-username: {{ required "client.kafka.sasl.username is required when SASL is enabled" .Values.client.kafka.sasl.username | quote }}
  kafka-sasl-password: {{ required "client.kafka.sasl.password is required when SASL is enabled" .Values.client.kafka.sasl.password | quote }}
  {{- end }}
