{{- if .Values.vector.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kg-rca-agent.fullname" . }}-vector
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kg-rca-agent.labels" . | nindent 4 }}
    component: vector
spec:
  type: ClusterIP
  ports:
    {{- if .Values.alertsWebhook.enabled }}
    - name: alerts-webhook
      port: {{ .Values.alertsWebhook.port }}
      targetPort: {{ .Values.alertsWebhook.port }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "kg-rca-agent.selectorLabels" . | nindent 4 }}
    component: vector
{{- end }}
