apiVersion: v1
kind: Namespace
metadata:
  name: observability
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: state-watcher
  namespace: observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: state-watcher
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "nodes", "events"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["apps"]
    resources: ["deployments", "replicasets", "daemonsets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: state-watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: state-watcher
subjects:
  - kind: ServiceAccount
    name: state-watcher
    namespace: observability
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: state-watcher
  namespace: observability
spec:
  replicas: 1
  selector:
    matchLabels: { app: state-watcher }
  template:
    metadata:
      labels: { app: state-watcher }
    spec:
      serviceAccountName: state-watcher
      containers:
        - name: state-watcher
          image: docker.io/anuragvishwa/state-watcher:0.4
          envFrom:
            - configMapRef:
                name: kgroot-env
          env:
            # Override specific values if needed
            - name: TOPIC_STATE
              valueFrom:
                configMapKeyRef:
                  name: kgroot-env
                  key: TOPIC_STATE_RESOURCE
            - name: TOPIC_TOPO
              valueFrom:
                configMapKeyRef:
                  name: kgroot-env
                  key: TOPIC_STATE_TOPOLOGY
          resources:
            requests: { cpu: "50m", memory: "64Mi" }
            limits: { memory: "128Mi" }
