apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  # Neo4j datasource
  - name: Neo4j
    type: neo4j-datasource
    access: proxy
    url: bolt://neo4j:7687
    isDefault: false
    editable: true
    secureJsonData:
      password: anuragvishwa
    jsonData:
      user: neo4j
      database: neo4j
