apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-v1
  namespace: buglab
  labels:
    scenario: configmap-outdated
immutable: true
data:
  config.yaml: |
    version: 1.0.0
    database_url: "old-db.example.com"
    feature_flags:
      new_feature: false
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-outdated-config
  namespace: buglab
  labels:
    app: bug-configmap
    scenario: configmap-outdated
spec:
  restartPolicy: Always
  containers:
    - name: app
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
        - |
          echo "Starting with configuration:"
          cat /config/config.yaml
          echo ""
          echo "App expects database_url: new-db.example.com"
          echo "App expects feature_flags.new_feature: true"
          echo "ERROR: Configuration mismatch!"
          while true; do
            echo "$(date) - Running with outdated config, errors expected..."
            sleep 20
          done
      volumeMounts:
        - name: config
          mountPath: /config
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi
  volumes:
    - name: config
      configMap:
        name: app-config-v1