apiVersion: v1
kind: Pod
metadata:
  name: init-container-fail
  namespace: buglab
  labels:
    app: bug-init
    scenario: init-fail
spec:
  restartPolicy: Always
  initContainers:
    - name: failing-init
      image: busybox:1.36
      command: ["sh", "-c"]
      args:
        - |
          echo "Init container attempting to connect to dependency..."
          echo "Simulating database migration failure"
          sleep 5
          exit 1
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi
  containers:
    - name: main-app
      image: nginx:1.25-alpine
      ports:
        - containerPort: 80
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi