apiVersion: v1
kind: Pod
metadata:
  name: port-conflict
  namespace: buglab
  labels:
    app: bug-port-conflict
    scenario: port-conflict
spec:
  restartPolicy: Always
  containers:
    - name: server-1
      image: nginx:1.25-alpine
      ports:
        - containerPort: 8080
          hostPort: 8080
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi
    - name: server-2
      image: nginx:1.25-alpine
      command: ["sh", "-c"]
      args:
        - |
          sed -i 's/listen       80;/listen       8080;/' /etc/nginx/conf.d/default.conf
          nginx -g 'daemon off;'
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 64Mi