apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nonexistent-storage
  namespace: buglab
  labels:
    scenario: pvc-pending
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nonexistent-storage-class
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-waiting-pvc
  namespace: buglab
  labels:
    app: bug-pvc
    scenario: pvc-pending
spec:
  restartPolicy: Always
  containers:
    - name: waiter
      image: busybox:1.36
      command: ["sh", "-c", "echo 'Waiting for PVC...'; sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
      resources:
        requests:
          cpu: 10m
          memory: 16Mi
        limits:
          cpu: 50m
          memory: 32Mi
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: pvc-nonexistent-storage