apiVersion: 1

datasources:
  # Prometheus datasource
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  # Neo4j datasource
  - name: Neo4j
    type: grafana-neo4j-datasource
    access: proxy
    url: bolt://neo4j:7687
    editable: true
    jsonData:
      encrypted: false
    secureJsonData:
      username: neo4j
      password: anuragvishwa
