global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'graph-builder'
    static_configs:
      - targets: ['graph-builder:9090']

  - job_name: 'neo4j'
    static_configs:
      - targets: ['neo4j:2004']
